name: massai mara park 01 docker ec2

on:
  workflow_dispatch

env:
  DOCKER_USERNAME: hdmksm1@naver.com
  IMAGE_NAME: massai_mara
  IMAGE_TAG: v${{ github.run_number }}
  EC2_HOSTNAME: 3.34.200.73
  EC2_USERNAME: ubuntu

jobs:
  build_image:
    runs-on: ubuntu-22.04-arm
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

    # arm64 에뮬레이션 - QEmu
      - name: setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: false
          load: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Check built image
        run: docker images

      - name: Save Docker image
        run: docker save ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -o image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

  hub_push:
    needs: build_image
    runs-on: ubuntu-22.04
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Check downloaded image
        run: ls -al

      - name: Load Docker image
        run: docker load < image.tar

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker operations
        run: |
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker tag ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          docker search ${{ env.IMAGE_NAME}}:latest

      - name: Logout from DockerHub
        if: always()
        run: docker logout

  upload_compose:
    needs: hub_push
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: copy file to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.EC2_HOSTNAME }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATEKEY }}
          port: 12137
          source: ./docker-compose-multijobs.yaml
          target: ~/docker-compose-multijobs.yaml

  run_test:
    needs: hub_push
    runs-on: ubuntu-22.04
    steps:
      - name: deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOSTNAME }}
          username: ${{ env.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATEKEY }}
          port: 12137
          script: |
            docker compose -f ./compose-multijobs.yaml up -d
            sleep 30

            docker compose ps
            docker compose logs
   